//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibraryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbPublication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DbPublication()
        {
            this.Authors = new HashSet<DbAuthor>();
            this.PhysicalLocations = new HashSet<DbBookLocation>();
            this.Course = new HashSet<DbCourse>();
            this.Discipline = new HashSet<DbDiscipline>();
            this.Stats = new HashSet<DbStats>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DatePublished { get; set; }
        public byte PublicationType { get; set; }
        public string Publisher { get; set; }
        public string InternetLocation { get; set; }
        public byte BookPublication { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbAuthor> Authors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbBookLocation> PhysicalLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbCourse> Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbDiscipline> Discipline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbStats> Stats { get; set; }
    }
}
