//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryDBContainer : DbContext
    {
        public LibraryDBContainer()
            : base("name=LibraryDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DbPublication> DbPublicationSet1 { get; set; }
        public virtual DbSet<DbAuthor> DbAuthorSet1 { get; set; }
        public virtual DbSet<DbBookLocation> DbBookLocationSet { get; set; }
        public virtual DbSet<DbReader> DbReaderSet { get; set; }
        public virtual DbSet<DbStats> DbStatsSet { get; set; }
        public virtual DbSet<DbCourse> DbCourseSet { get; set; }
        public virtual DbSet<DbDiscipline> DbDisciplineSet { get; set; }
    }
}
